### ISSUE TITLE
refactor: 거래 후기 작성 페이지 리팩토링

### ISSUE THREAD

**Issue by hj9118** [Programmers-HandsUp/FE-HandsUp#130]
## 배경

- 이전 버전 머지 이후 리팩토링 진행

## TODO

- [x] Chips 이미지 변경
- [ ] textarea(후기 텍스트) 스크롤 수정
- [ ] tanstack-query 추가
- [x] 상품카드 영역 변경 코드 팔로업
