### ISSUE TITLE
design: 이미지 추가 및 생성

### ISSUE THREAD

**Issue by hj9118** [Programmers-HandsUp/FE-HandsUp#191]
## TODO

- [ ] 텍스트 로고 오타 수정
- [ ] 스플래시용 이미지 추가
- [ ] 마이페이지용 이미지 추가
- [ ] 파비콘 수정
- [ ] webp 확장자 사용
