### ISSUE TITLE
fix: 기능 테스트 후 버그 수정

### ISSUE THREAD

**Issue by imssein** [Programmers-HandsUp/FE-HandsUp#264]
## 배경

기능 테스트 점검시 발생한 버그 수정

## TODO

- [x] 리뷰 라벨 value 수정
- [x] 상품 등록 - 상품 상세 엔터 안됨 
- [x] 상품 등록 - 초기화 버튼 클린한 경우 입력한 게시물 전체 초기화되는 현상
- [x] 알림 - staletime 변경
- [ ] 상품 등록 validation 확인
