### ISSUE TITLE
fix : 검색 필터 중 거래방식 적용 오류 수정 및 검색 카드 디자인 요소 추가

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#272]
## 배경
 검색 필터 중 거래방식 적용 오류 수정 및 검색 카드 디자인 요소 추가

## TODO

- [x] 검색 필터 중 거래방식 적용 오류 수정
- [x] 택배 선호 거래 물품인 경우 택배 태그 부착하기 
- [x] 검색카드에서 전체적으로 text 수정하기
