### ISSUE TITLE
design : 로그인 & 회원가입 & 검색 페이지 - PC웹 환경 페이지 디자인  (반응형)

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#285]
## 배경
현재 저희 프로젝트는 **모바일 웹 환경 기준으로만** 디자인 되어있습니다.
그래서 이번에 제가 맡아 개발한 페이지 먼저 PC 웹 환경 디자인(반응형)을 추가하려합니다. 

## TODO

- [ ] 로그인 페이지 PC 웹 환경 디자인 
- [ ] 회원가입 페이지 PC 웹 환경 디자인
- [ ] 검색 페이지 PC 웹 환경 디자인
