### ISSUE TITLE
refactor : 검색페이지 - 검색 결과 필터 설정 모달 리펙토링, 디자인 변경 및 버그 수정

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#287]
## 배경
 검색페이지에 필터 설정 모달 디자인이 매우 구린거 같아 이쁘게 꾸미려합니다.
또 한, 현재 필터 조건들을 여러개의 state로 관리하여 한 눈에 파악하기 힘들고, state 갯수가 많은 만큼 유효성 검사 관련 코드 또 한, 양이 많고 복잡합니다. 
그래서 이 부분을 react-hook-form과 zod를 이용하여 리펙토링 해볼 예정입니다.

## TODO
- 리펙토링 
  - [ ] 기존 필터 관련 조건들 state로 관리하고 있지만, `react-hook-form` 사용방식으로 변경
  - [ ] form 유효성 검사를 위한 `zod` 적용
- 디자인 변경
   - [ ] 검색 결과 필터 설정 모달 디자인 변경

- 버그 수정
   - [ ] 카테고리 두 개 이상 선택되는 버그 수정 <br/> <img width="347" alt="image" src="https://github.com/Programmers-HandsUp/FE-HandsUp/assets/40955023/1f0b1ac1-10f3-455f-9e2f-877da056164e">
