### ISSUE TITLE
settings & refactor : 프로젝트 전반적인 로직에 MSW 적용 및 재구축 

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#290]
### 프로젝트 전반적인 로직에 MSW 적용 및 재구축 
 기존 배포된 백엔드 서버가 프로그래머스에서 지원 끝난 이후 가현님 개인 계정 배포 서버로 이전되었습니다.
현재 **비용 문제** 이유로 상시 서버 구동이 힘든 이유로 가현님이 부재중일 때도 개발을 이어나갈 수 있도록 MSW를 재구축 하려합니다.

현재 제가 프로젝트를 둘러보고 느낀 개선해보면 좋을 사항들은...
1. 기존 mocking api들 최신화하기 
 (실제 사용되는 백엔드 api들의 response 와 mocking Api의 response가 일치하지 않은게 다수 있습니다. - 특히 `field 명`)
2. Test용 mocking 코드 추가하기 
3. API Mocking과 실제 API 스위칭 쉽게 할 수 있는 기능 구현

### 기대효과 
1. 백엔드 서버가 켜져있지 않아도 개발을 이어나갈 수 있음.  + 백엔드 api 없이 실험용 코드 짜볼수 있을거같음.
2. 만들어둔 mokcing api, data 코드들이 추후 통합 테스트 / E2E 테스트 사용할 때 유용하게 쓰일 수 있을거 같음.
( 참고  - [MSW를 활용하는 Front-End 통합테스트 - 카카오 기술블로그 ](https://fe-developers.kakaoent.com/2022/220825-msw-integration-testing/))

## TODO

- [ ] 기존 mocking api들 최신화하기
- [ ] Test용 mocking 코드 추가하기  
- [ ] API Mocking과 실제 API 스위칭 쉽게 할 수 있는 기능 구현
