### ISSUE TITLE
Accessibility : HandsUp 프로젝트 전체적인 LightHouse 최적화 작업

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#296]
## 배경
HandsUp 프로젝트 전체적인 LightHouse 최적화 작업

## TODO

- [ ] 메인 홈 최적화 작업
- [ ] 검색 페이지 최적화 작업
- [ ] 마이페이지 최적화 작업 
- [ ] 로그인 & 회원가입 페이지 최적화 작업
- [ ] 경매 상세물품 페이지 최적화 작업
