### ISSUE TITLE
fix : 파일명에 대소문자 구분 관련 빌드 오류 & 로그인 후 토큰 저장 안되는 버그 수정 

### ISSUE THREAD

**Issue by JuJangGwon** [Programmers-HandsUp/FE-HandsUp#299]
### 1. SignUpHeader.ts 파일명 충돌 이슈 
현재 SignUpHeader.ts파일에서 빌드 에러가 뜨고 있습니다.  원인으로는 제가 기존 SignupHeader.ts 파일의 이름을 SignUpHeader.ts 로 변경했는데   
깃이 파일의 대소문자 변경을 감지하지 못하기 특성 탓에, 원격저장소에 있는 파일과 충돌나서 현재 배포 빌드 오류가 뜨고 있습니다.

제 eslint나 빌드했을 때 에러가 잡히지 않아서 어떤 원인으로 배포를 실패하나 했더니 이 이유더군요.

<br/>
<br/>

### 2.  로그인 후 토큰이 쿠키에 저장 안되는 버그 수정 
#295  이떄 모킹 코드 작성하면서 로그인 api와 유저 정보 불러오는 api를 살짝 수정했는데 이떄 토큰을 쿠키에 저장 하는 코드를 누락시킨거 같습니다.
확인하고 pr올렸어야했는데...

<br/>

## TODO

- [ ] 로그인 APi 응답 성공시 토큰 쿠키에 저장 
- [ ] 회원가입 APi 응답 성공시 토큰 쿠키에 저장 
- [ ] SignUpHeader.ts 파일 명 변경
