### ISSUE TITLE
feat: 채팅 메세지 컴포넌트 구현

### ISSUE THREAD

**Issue by hj9118** [Programmers-HandsUp/FE-HandsUp#50]
## 배경

- 채팅 메세지에서 사용할 메세지 컴포넌트 구현 요구
- 이용자가 전송한 메세지, 상대방이 전송한 메세지 디자인이 다를 것.
- 여러줄 전송해도 디자인이 비슷하게 나올 것

![image](https://github.com/Programmers-HandsUp/FE-HandsUp/assets/104545906/ecb1702e-fd38-4ae3-98e8-304cca3fb1b2)

## TODO

- [ ] 상대방 아바타, 메세지 한번에 표현되도록 구성
- [ ] 여러건의 메세지가 전송될 경우 한번만 아바타 표시 띄우게 제작
- [ ] 내 메세지는 우측 정렬 및 메인색상 사용
